# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9aed482c81308daf8d562e6e55358674aa90d2d3cb3a6b367265f7160a11a15d4eff3d89fa5d36d6f7c72401921e7bd6bb3b52b75009d21d30474d3bdc65640

test:
  secret_key_base: 18bad3f0bca380cca22c001dade5cd5209f8826f352c1b9983981be9d423ed15ab47ab0e86092292a4c25233185899678254c48a5ca0d518ffd9c359de9527d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
